# Generated by Django 4.2.6 on 2023-11-05 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('model', models.CharField(max_length=255)),
                ('ups_type', models.CharField(max_length=255)),
                ('battery_capacity', models.IntegerField()),
                ('battery_temperature', models.IntegerField()),
                ('battery_runtime_remain', models.BigIntegerField()),
                ('battery_replace', models.BooleanField()),
                ('battery_type', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room_temperature', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('building_name', models.CharField(max_length=255)),
                ('lan_room', models.CharField(max_length=255)),
                ('battery_installed_date', models.DateField()),
                ('ups_installed_date', models.DateField()),
                ('battery_count', models.IntegerField()),
                ('management', models.CharField(max_length=255)),
                ('last_modified_user', models.CharField(max_length=255)),
                ('last_modified_date', models.DateTimeField()),
                ('battery_type', models.CharField(max_length=255)),
                ('snmp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ups.snmp')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=255)),
                ('ups_type', models.CharField(max_length=255)),
                ('battery_capacity', models.IntegerField()),
                ('battery_temperature', models.IntegerField()),
                ('battery_runtime_remain', models.BigIntegerField()),
                ('battery_replace', models.BooleanField()),
                ('battery_type', models.CharField(max_length=255)),
                ('snmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ups.snmp')),
            ],
        ),
    ]
